<a href="https://colab.research.google.com/github/Aravind-190905/learningpytorch/blob/main/00pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


## **pytorch-00**
the course we follow is [https://www.youtube.com/watch?v=V_xro1bcAuA&t=3467s](https://)


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.8.0+cu126


# creating tensors


In [4]:
#scalar
scalar=torch.tensor(7)


In [5]:
scalar.ndim ## the dimension of the scalar is 0.
scalar.item()## get our number back from the tensor.

7

In [6]:
##vector
vector=torch.tensor([3,2])
vector.ndim
vector.shape ## the shape means the rows and columns.

torch.Size([2])

## what shape means!
shape of a tensor which is basically a matrix here is the number of elements in each direction. say for [1,3,4] the dimension is (3,) and for [[1,3,4],[2,35,4]] the shape is 2 in 1 st tensor and 3 elements in the tensor inside it. hence the size / shape is (2,3)

In [7]:
## matrix
mat=torch.tensor([[1,2],[4,5]])
mat.ndim  ## the dimension is 2
mat.shape

torch.Size([2, 2])

In [8]:
## TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[4,6,5]]])
TENSOR.ndim
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [4, 6, 5]])

# random tensors

why random tensors??
random tensors are important the way many neural networks work is they eat a lot of random tensors and learn.


In [9]:
#create the RANDOM TENSOR tensor of size (3,4)
rand_tensor=torch.rand(3,4)
rand_tensor

tensor([[0.9803, 0.4176, 0.6227, 0.4872],
        [0.8821, 0.7489, 0.6147, 0.3277],
        [0.0085, 0.8448, 0.2848, 0.4993]])

In [10]:
## create a random tensor with similar shape to an image tensor
img=torch.rand(size=(224,224,3))# let it be the height,width and color channel.
# we have red green and blue and we got two dimensions of the image.


In [11]:
## create a tensor of all zeros.
s=torch.zeros(3,4)
s
## we can also make ones
m=torch.ones(2,2)
m

tensor([[1., 1.],
        [1., 1.]])

## creating a tensor in a given range :


In [12]:
## use the torch.range()
ang=torch.arange(start=2,end=10,step=2)
ang   ## step is like jumping.

tensor([2, 4, 6, 8])

In [13]:
## tensor like another one
tensor_zero=torch.zeros_like(ang)
tensor_zero

tensor([0, 0, 0, 0])

# tensor datatypes

In [14]:
float_32_tensor=torch.tensor([1.0,2.0,3.0,4.0],dtype=None,device="cpu",requires_grad=False)
float_32_tensor.dtype
# ml models usually use the float datatype
## here new attribute device where u store the tesor at cpu or cuda (gpu)
# require_grad= means to automatically keep the tracking of the gradient.

torch.float32

 ## a recap
we have a **MAJOR** function
torch.tensor used to make tensors.
fill em with zeros and ones of given size torch.zeros and ones.

In [15]:
## major errors in tensors are
# the shape of two tensors not being same
# not the datatype .
# not on the same device.

In [16]:
#type conversions
float_16_tensor=float_32_tensor.type(torch.float16)


In [17]:
mul=float_16_tensor*float_32_tensor
mul

tensor([ 1.,  4.,  9., 16.])

In [18]:
some_ten=torch.rand(3,4)
some_ten

tensor([[0.5002, 0.8054, 0.5541, 0.7719],
        [0.9569, 0.5984, 0.1038, 0.9260],
        [0.0740, 0.3075, 0.1019, 0.2432]])

**the major difference between shape and the size of a tensor is shape is an  attribute where as the size is a function**

In [19]:
some_ten.size()
some_ten.shape

torch.Size([3, 4])

In [20]:
some_ten.dtype ## dtype is also an attribute and default its 32.
some_ten.device  ## this is also and attribute

device(type='cpu')

## tenosr operations
includes the operations such as
*addition*
*substraction*
*multiplication*
and *matrix multiplication*

## **ADDITION**

In [21]:
#create a tensor
tensor=torch.tensor([1,3,4])
tensor/10
tensor+10
tensor-10
tensor*10
## these are all the scalar operations

tensor([10, 30, 40])

In [22]:
## we also have function of torch
torch.add(tensor,3)
torch.mul(tensor,4)
torch.div(tensor,2)
torch.sub(tensor,2)

tensor([-1,  1,  2])

## **matrix multiplication**
few sublte points in matrix mutliplication in pytorch.

*   when we matrix multiply two single dimensional tensors it does    dot  product btw them. (A@B)
*   any dimension more than that we use the MATRIX MULTIPLICATION RULE.
*   the multiplication rule is m&n and n&m should be the sizes of  matrices.

* we can also use **torch.matmul()**



In [23]:
t1=torch.tensor([2,4,5])
t2=torch.tensor([1,3,4])
t1@t2

tensor(34)

In [24]:
ta=torch.tensor([[1,3],[1,2],[1,3]])
print(ta.shape)
tb=torch.tensor([[1,3,4],[1,2,3]])
print(tb.shape)
ta@tb

torch.Size([3, 2])
torch.Size([2, 3])


tensor([[ 4,  9, 13],
        [ 3,  7, 10],
        [ 4,  9, 13]])

In [25]:
## lets see what happens when we mutliply ta and t1
t1@ta
## which is not the same as ta @ t1 hence the same matrix rule.

tensor([11, 29])

In [26]:
## then there is the basic mutliplication of element matching.
print(t1*t2)
## print(ta*tb) this wont happen cause we cant match the elenments.

tensor([ 2, 12, 20])


In [27]:
torch.mm(ta,tb)   ## matmul and mm same thing.

tensor([[ 4,  9, 13],
        [ 3,  7, 10],
        [ 4,  9, 13]])

## we can time things using %% time


##transpose of matrix


In [28]:
ta.T # t is always capital.

tensor([[1, 1, 1],
        [3, 2, 3]])

## find the min max mean etc (tensor aggregration)

In [29]:
## tensor
x=torch.arange(0,100,1)
torch.min(x) ## we can use the torch function or
x.min()

tensor(0)

* **TYPE CASTING FOR TENSOR IS DONE USING THE FUNCTION *TO()***

In [30]:
## for the mean funciton we need to have float or complex dtype.
x=x.to(torch.float32) ## its always torch.float32.


In [31]:
## find the mean
torch.mean(x),x.mean()  ## MEAN ALWAYS NEED A FLOAT OR COMPLEX TENSOR .

(tensor(49.5000), tensor(49.5000))

In [32]:
## sum adds all the elements
torch.sum(x),x.sum()


(tensor(4950.), tensor(4950.))

In [33]:
## tensor.argmin(),argmax() are function that give the indices of min and max.
x.argmin(),torch.argmin(x)
x.argmax(),torch.argmax(x)

(tensor(99), tensor(99))

## reshaping stacking squeezing and unsqeezing tensors
* reshaping- changing the shape of the tensor.
* stacking
* cat
* squeeze
* unsqueeze

In [34]:
# how to add an extra dimension.
x=torch.arange(1.,10.)
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [35]:
#change the view.
z=x.view(1,9)


 **view is basically like reshape but when u store it in another variable it "shares " the memory so when we change z in the above example it must change x.**


In [36]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

## **STACKING VS CAT**
* torch.stack() is a function that adds one tensor to other in a really specific way.say we have two tensors [1,3,4],[3,4,5]. STACKING means to create a tensor that stores both of the tensors together. we can add new dimension. [[1,3,4],[3,4,5]]

* stack() takes a tuple and **dim as arguments**. here dim means axis.hence we wanna stack column wise we can use dim 1.

* **stacking requires the tensors to be of same size**

*torch.cat() just appends two tensors.
[1,3,4,3,4,5]


In [51]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
#torch.stack([a,b])

In [50]:
torch.cat([a,b])



tensor([1, 2, 3, 4, 4, 5, 6])

In [44]:
ans=torch.stack([a,b],dim=1)
ans

tensor([[1, 4],
        [2, 5],
        [3, 6]])


## unsqueeze and squeeze
 unsqueeze does increase the dimnesion of the tensor. squeeze does the opposite.


In [59]:
torch.squeeze(a,dim=0)

tensor([1, 2, 3])

## permute
torch.permute() returns view

In [65]:
ta=torch.tensor([[1,2,3],[4,5,6]])
ta.shape

torch.Size([2, 3])

In [70]:
timg=torch.rand(size=[2,2,3])
timg

tensor([[[0.1730, 0.9510, 0.2121],
         [0.4180, 0.8596, 0.9146]],

        [[0.2985, 0.8591, 0.3292],
         [0.3024, 0.7823, 0.9817]]])

In [72]:
timg.reshape(shape=[3,2,2])

tensor([[[0.1730, 0.9510],
         [0.2121, 0.4180]],

        [[0.8596, 0.9146],
         [0.2985, 0.8591]],

        [[0.3292, 0.3024],
         [0.7823, 0.9817]]])

In [73]:
timg.permute(2,0,1)

tensor([[[0.1730, 0.4180],
         [0.2985, 0.3024]],

        [[0.9510, 0.8596],
         [0.8591, 0.7823]],

        [[0.2121, 0.9146],
         [0.3292, 0.9817]]])

In [77]:
x = torch.tensor([[[1,2,3],
                  [4,5,6]],[[7,8,9],[10,11,12]]])

In [81]:
x.permute(0,1,2)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [82]:
x.permute(0,2,1)

tensor([[[ 1,  4],
         [ 2,  5],
         [ 3,  6]],

        [[ 7, 10],
         [ 8, 11],
         [ 9, 12]]])

## indexing in tensors
* same as the numpy indexing.


In [103]:
ten1=torch.arange(1,10).reshape(1,3,3)
ten1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [95]:
## lets indeex
ten1[0,2,2]
## indexing in python always starts with 0

tensor(9)

In [98]:
## slicing
ten1[:,1,:] ## this gives the first row in all the matrices.
## give a particular column
ten1[0,:,1]
## we can always print the whole thing using
ten1[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [100]:
## we can also do this
ten1[0][0] # note that the zeroth dimension for this is from the left.

tensor([1, 2, 3])

In [101]:
ten1[0][2][2]

tensor(9)

## practice

In [109]:
# all elements of 0 and 1 dimensions and 2nd of 2nd
ten1[:,:,2]

tensor([[3, 6, 9]])

In [114]:
ten1[:][0][0]

tensor([1, 2, 3])