<a href="https://colab.research.google.com/github/Aravind-190905/learningpytorch/blob/main/00pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


## **pytorch-00**
the course we follow is [https://www.youtube.com/watch?v=V_xro1bcAuA&t=3467s](https://)


In [9]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.8.0+cu126


# creating tensors


In [10]:
#scalar
scalar=torch.tensor(7)


In [11]:
scalar.ndim ## the dimension of the scalar is 0.
scalar.item()## get our number back from the tensor.

7

In [12]:
##vector
vector=torch.tensor([3,2])
vector.ndim
vector.shape ## the shape means the rows and columns.

torch.Size([2])

## what shape means!
shape of a tensor which is basically a matrix here is the number of elements in each direction. say for [1,3,4] the dimension is (3,) and for [[1,3,4],[2,35,4]] the shape is 2 in 1 st tensor and 3 elements in the tensor inside it. hence the size / shape is (2,3)

In [13]:
## matrix
mat=torch.tensor([[1,2],[4,5]])
mat.ndim  ## the dimension is 2
mat.shape

torch.Size([2, 2])

In [14]:
## TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[4,6,5]]])
TENSOR.ndim
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [4, 6, 5]])

# random tensors

why random tensors??
random tensors are important the way many neural networks work is they eat a lot of random tensors and learn.


In [15]:
#create the RANDOM TENSOR tensor of size (3,4)
rand_tensor=torch.rand(3,4)
rand_tensor

tensor([[0.6313, 0.1559, 0.6116, 0.5325],
        [0.6114, 0.7403, 0.9453, 0.1016],
        [0.5433, 0.6334, 0.5610, 0.9575]])

In [16]:
## create a random tensor with similar shape to an image tensor
img=torch.rand(size=(224,224,3))# let it be the height,width and color channel.
# we have red green and blue and we got two dimensions of the image.


In [17]:
## create a tensor of all zeros.
s=torch.zeros(3,4)
s
## we can also make ones
m=torch.ones(2,2)
m

tensor([[1., 1.],
        [1., 1.]])

## creating a tensor in a given range :


In [18]:
## use the torch.range()
ang=torch.arange(start=2,end=10,step=2)
ang   ## step is like jumping.

tensor([2, 4, 6, 8])

In [19]:
## tensor like another one
tensor_zero=torch.zeros_like(ang)
tensor_zero

tensor([0, 0, 0, 0])

# tensor datatypes

In [20]:
float_32_tensor=torch.tensor([1.0,2.0,3.0,4.0],dtype=None,device="cpu",requires_grad=False)
float_32_tensor.dtype
# ml models usually use the float datatype
## here new attribute device where u store the tesor at cpu or cuda (gpu)
# require_grad= means to automatically keep the tracking of the gradient.

torch.float32

 ## a recap
we have a **MAJOR** function
torch.tensor used to make tensors.
fill em with zeros and ones of given size torch.zeros and ones.

In [21]:
## major errors in tensors are
# the shape of two tensors not being same
# not the datatype .
# not on the same device.

In [22]:
#type conversions
float_16_tensor=float_32_tensor.type(torch.float16)


In [23]:
mul=float_16_tensor*float_32_tensor
mul

tensor([ 1.,  4.,  9., 16.])

In [24]:
some_ten=torch.rand(3,4)
some_ten

tensor([[0.2239, 0.9001, 0.4352, 0.9224],
        [0.4799, 0.4903, 0.6083, 0.9365],
        [0.4725, 0.5500, 0.6194, 0.1917]])

**the major difference between shape and the size of a tensor is shape is an  attribute where as the size is a function**

In [25]:
some_ten.size()
some_ten.shape

torch.Size([3, 4])

In [26]:
some_ten.dtype ## dtype is also an attribute and default its 32.
some_ten.device  ## this is also and attribute

device(type='cpu')

## tenosr operations
includes the operations such as
*addition*
*substraction*
*multiplication*
and *matrix multiplication*

## **ADDITION**

In [27]:
#create a tensor
tensor=torch.tensor([1,3,4])
tensor/10
tensor+10
tensor-10
tensor*10
## these are all the scalar operations

tensor([10, 30, 40])

In [28]:
## we also have function of torch
torch.add(tensor,3)
torch.mul(tensor,4)
torch.div(tensor,2)
torch.sub(tensor,2)

tensor([-1,  1,  2])

## **matrix multiplication**
few sublte points in matrix mutliplication in pytorch.

*   when we matrix multiply two single dimensional tensors it does    dot  product btw them. (A@B)
*   any dimension more than that we use the MATRIX MULTIPLICATION RULE.
*   the multiplication rule is m&n and n&m should be the sizes of  matrices.

* we can also use **torch.matmul()**



In [29]:
t1=torch.tensor([2,4,5])
t2=torch.tensor([1,3,4])
t1@t2

tensor(34)

In [30]:
ta=torch.tensor([[1,3],[1,2],[1,3]])
print(ta.shape)
tb=torch.tensor([[1,3,4],[1,2,3]])
print(tb.shape)
ta@tb

torch.Size([3, 2])
torch.Size([2, 3])


tensor([[ 4,  9, 13],
        [ 3,  7, 10],
        [ 4,  9, 13]])

In [31]:
## lets see what happens when we mutliply ta and t1
t1@ta
## which is not the same as ta @ t1 hence the same matrix rule.

tensor([11, 29])

In [32]:
## then there is the basic mutliplication of element matching.
print(t1*t2)
## print(ta*tb) this wont happen cause we cant match the elenments.

tensor([ 2, 12, 20])


In [33]:
torch.mm(ta,tb)   ## matmul and mm same thing.

tensor([[ 4,  9, 13],
        [ 3,  7, 10],
        [ 4,  9, 13]])

## we can time things using %% time


##transpose of matrix


In [34]:
ta.T # t is always capital.

tensor([[1, 1, 1],
        [3, 2, 3]])

## find the min max mean etc (tensor aggregration)

In [40]:
## tensor
x=torch.arange(0,100,1)
torch.min(x) ## we can use the torch function or
x.min()

tensor(0)

* **TYPE CASTING FOR TENSOR IS DONE USING THE FUNCTION *TO()***

In [53]:
## for the mean funciton we need to have float or complex dtype.
x=x.to(torch.float32) ## its always torch.float32.


In [56]:
## find the mean
torch.mean(x),x.mean()  ## MEAN ALWAYS NEED A FLOAT OR COMPLEX TENSOR .

(tensor(49.5000), tensor(49.5000))

In [62]:
## sum adds all the elements
torch.sum(x),x.sum()


(tensor(4950.), tensor(4950.))

In [71]:
## tensor.argmin(),argmax() are function that give the indices of min and max.
x.argmin(),torch.argmin(x)
x.argmax(),torch.argmax(x)

(tensor(99), tensor(99))