<a href="https://colab.research.google.com/github/Aravind-190905/learningpytorch/blob/main/00pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


## **pytorch-00**
the course we follow is [https://www.youtube.com/watch?v=V_xro1bcAuA&t=3467s](https://)


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.8.0+cu126


# creating tensors


In [4]:
#scalar
scalar=torch.tensor(7)


In [5]:
scalar.ndim ## the dimension of the scalar is 0.
scalar.item()## get our number back from the tensor.

7

In [6]:
##vector
vector=torch.tensor([3,2])
vector.ndim
vector.shape ## the shape means the rows and columns.

torch.Size([2])

In [7]:
## matrix
mat=torch.tensor([[1,2],[4,5]])
mat.ndim  ## the dimension is 2
mat.shape

torch.Size([2, 2])

In [8]:
## TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[4,6,5]]])
TENSOR.ndim
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [4, 6, 5]])

# random tensors

why random tensors??
random tensors are important the way many neural networks work is they eat a lot of random tensors and learn.


In [9]:
#create the RANDOM TENSOR tensor of size (3,4)
rand_tensor=torch.rand(3,4)
rand_tensor

tensor([[0.8892, 0.4690, 0.1912, 0.4830],
        [0.2428, 0.8139, 0.1603, 0.5972],
        [0.0540, 0.2284, 0.7048, 0.7296]])

In [10]:
## create a random tensor with similar shape to an image tensor
img=torch.rand(size=(224,224,3))# let it be the height,width and color channel.
# we have red green and blue and we got two dimensions of the image.


In [11]:
## create a tensor of all zeros.
s=torch.zeros(3,4)
s
## we can also make ones
m=torch.ones(2,2)
m

tensor([[1., 1.],
        [1., 1.]])

## creating a tensor in a given range :


In [12]:
## use the torch.range()
ang=torch.arange(start=2,end=10,step=2)
ang   ## step is like jumping.

tensor([2, 4, 6, 8])

In [13]:
## tensor like another one
tensor_zero=torch.zeros_like(ang)
tensor_zero

tensor([0, 0, 0, 0])

# tensor datatypes

In [14]:
float_32_tensor=torch.tensor([1.0,2.0,3.0,4.0],dtype=None,device="cpu",requires_grad=False)
float_32_tensor.dtype
# ml models usually use the float datatype
## here new attribute device where u store the tesor at cpu or cuda (gpu)
# require_grad= means to automatically keep the tracking of the gradient.

torch.float32

 ## a recap
we have a **MAJOR** function
torch.tensor used to make tensors.
fill em with zeros and ones of given size torch.zeros and ones.

In [15]:
## major errors in tensors are
# the shape of two tensors not being same
# not the datatype .
# not on the same device.

In [18]:
#type conversions
float_16_tensor=float_32_tensor.type(torch.float16)


'torch.HalfTensor'

In [19]:
mul=float_16_tensor*float_32_tensor
mul

tensor([ 1.,  4.,  9., 16.])

In [26]:
some_ten=torch.rand(3,4)
some_ten

tensor([[0.7988, 0.1181, 0.2504, 0.3366],
        [0.7002, 0.0406, 0.7420, 0.8356],
        [0.9037, 0.8128, 0.5915, 0.5611]])

**the major difference between shape and the size of a tensor is shape is an  attribute where as the size is a function**

In [29]:
some_ten.size()
some_ten.shape

torch.Size([3, 4])

In [31]:
some_ten.dtype ## dtype is also an attribute and default its 32.
some_ten.device  ## this is also and attribute

device(type='cpu')

## tenosr operations
includes the operations such as
*addition*
*substraction*
*multiplication*
and *matrix multiplication*

## **ADDITION**

In [34]:
#create a tensor
tensor=torch.tensor([1,3,4])
tensor/10
tensor+10
tensor-10
tensor*10
## these are all the scalar operations

tensor([10, 30, 40])

In [39]:
## we also have function of torch
torch.add(tensor,3)
torch.mul(tensor,4)
torch.div(tensor,2)
torch.sub(tensor,2)

tensor([-1,  1,  2])

## **matrix multiplication**

In [47]:
## two main ways of perfroming the multiplication.
